/*
 *                     GNU AFFERO GENERAL PUBLIC LICENSE
 *                        Version 3, 19 November 2007
 *
 *  Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
 *  Everyone is permitted to copy and distribute verbatim copies
 *  of this license document, but changing it is not allowed.
 */
package com.jdimension.jlawyer.client.editors.files;

import com.jdimension.jlawyer.persistence.PaymentSplitProposal;
import java.awt.Color;
import java.awt.Dimension;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 * Dialog for manually adjusting payment split allocations.
 *
 * @author jens
 */
public class PaymentSplitEditDialog extends javax.swing.JDialog {

    private PaymentSplitProposal proposal;
    private boolean modified = false;
    private DecimalFormat currencyFormat = new DecimalFormat("#,##0.00");
    private PaymentSplitEditTableModel tableModel;

    /**
     * Creates new form PaymentSplitEditDialog
     */
    public PaymentSplitEditDialog(JDialog parent, boolean modal, PaymentSplitProposal proposal) {
        super(parent, modal);
        this.proposal = proposal;
        initComponents();

        // Set size and center
        setPreferredSize(new Dimension(700, 500));
        pack();
        setLocationRelativeTo(parent);

        // Initialize table model
        tableModel = new PaymentSplitEditTableModel(proposal.getAllocations(), proposal.getTotalAmount());
        tblEdit.setModel(tableModel);

        // Set column widths
        tblEdit.getColumnModel().getColumn(0).setPreferredWidth(250); // Komponente
        tblEdit.getColumnModel().getColumn(1).setPreferredWidth(120); // Offen
        tblEdit.getColumnModel().getColumn(2).setPreferredWidth(120); // Zahlung

        // Add table model listener to update summary
        tableModel.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                updateSummary();
            }
        });

        // Initial summary update
        updateSummary();
    }

    private void updateSummary() {
        BigDecimal total = tableModel.getTotalAvailable();
        BigDecimal allocated = tableModel.getTotalAllocated();
        BigDecimal remaining = tableModel.getRemaining();

        lblAvailable.setText("Verfügbar: " + currencyFormat.format(total) + " €");
        lblAllocated.setText("Verteilt: " + currencyFormat.format(allocated) + " €");
        lblRemaining.setText("Rest: " + currencyFormat.format(remaining) + " €");

        // Color coding for remaining amount
        if (remaining.compareTo(BigDecimal.ZERO) == 0) {
            lblRemaining.setForeground(new Color(0, 128, 0)); // Green
            lblWarning.setText("");
        } else if (remaining.compareTo(BigDecimal.ZERO) > 0) {
            lblRemaining.setForeground(Color.ORANGE);
            lblWarning.setText("⚠ Warnung: Nicht der gesamte Betrag wurde verteilt!");
        } else {
            lblRemaining.setForeground(Color.RED);
            lblWarning.setText("⚠ Fehler: Verteilter Betrag übersteigt verfügbaren Betrag!");
        }

        // Check if follows legal order
        // TODO: Implement check against automatic proposal
        lblLegalWarning.setText("ℹ Hinweis: Abweichung von gesetzlicher Reihenfolge (§ 366/367 BGB)");
        lblLegalWarning.setVisible(!proposal.isFollowsLegalOrder());
    }

    public boolean isModified() {
        return modified;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblAvailable = new javax.swing.JLabel();
        lblAllocated = new javax.swing.JLabel();
        lblRemaining = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEdit = new javax.swing.JTable();
        lblWarning = new javax.swing.JLabel();
        lblLegalWarning = new javax.swing.JLabel();
        cmdCancel = new javax.swing.JButton();
        cmdOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zahlungsverteilung manuell anpassen");

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel1.setText("Passen Sie die Verteilung der Zahlung auf die Komponenten an:");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAvailable.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblAvailable.setText("Verfügbar: 0,00 €");

        lblAllocated.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblAllocated.setText("Verteilt: 0,00 €");

        lblRemaining.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblRemaining.setText("Rest: 0,00 €");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvailable)
                .addGap(18, 18, 18)
                .addComponent(lblAllocated)
                .addGap(18, 18, 18)
                .addComponent(lblRemaining)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvailable)
                    .addComponent(lblAllocated)
                    .addComponent(lblRemaining))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblEdit);

        lblWarning.setForeground(new java.awt.Color(255, 102, 0));
        lblWarning.setText(" ");

        lblLegalWarning.setForeground(new java.awt.Color(255, 102, 0));
        lblLegalWarning.setText(" ");

        cmdCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        cmdCancel.setText("Abbrechen");
        cmdCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelActionPerformed(evt);
            }
        });

        cmdOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/agt_action_success.png"))); // NOI18N
        cmdOk.setText("Übernehmen");
        cmdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cmdOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdCancel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLegalWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLegalWarning)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdCancel)
                    .addComponent(cmdOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelActionPerformed
        modified = false;
        dispose();
    }//GEN-LAST:event_cmdCancelActionPerformed

    private void cmdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOkActionPerformed
        if (!tableModel.isValid()) {
            JOptionPane.showMessageDialog(this,
                    "Die Summe der verteilten Beträge muss genau dem Zahlungsbetrag entsprechen!",
                    "Ungültige Verteilung",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Update proposal with modified allocations
        proposal.setAllocations(tableModel.getAllocations());
        proposal.setManuallyAdjusted(true);
        // Note: Would need to check against automatic proposal to determine if still follows legal order
        proposal.setFollowsLegalOrder(false); // Conservative assumption

        modified = true;
        dispose();
    }//GEN-LAST:event_cmdOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAllocated;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblLegalWarning;
    private javax.swing.JLabel lblRemaining;
    private javax.swing.JLabel lblWarning;
    private javax.swing.JTable tblEdit;
    // End of variables declaration//GEN-END:variables
}
