/*
 *                     GNU AFFERO GENERAL PUBLIC LICENSE
 *                        Version 3, 19 November 2007
 *
 *  Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
 *  Everyone is permitted to copy and distribute verbatim copies
 *  of this license document, but changing it is not allowed.
 */
package com.jdimension.jlawyer.client.editors.files;

import com.jdimension.jlawyer.persistence.PaymentSplitProposal;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;

/**
 * Dialog for previewing a payment split proposal before creating the entries.
 *
 * @author jens
 */
public class PaymentSplitPreviewDialog extends javax.swing.JDialog {

    private PaymentSplitProposal proposal;
    private boolean approved = false;
    private DecimalFormat currencyFormat = new DecimalFormat("#,##0.00 €");
    private SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");

    /**
     * Creates new form PaymentSplitPreviewDialog
     */
    public PaymentSplitPreviewDialog(JDialog parent, boolean modal, PaymentSplitProposal proposal) {
        super(parent, modal);
        this.proposal = proposal;
        initComponents();

        // Set size and center
        setPreferredSize(new Dimension(800, 600));
        pack();
        setLocationRelativeTo(parent);

        // Populate data
        populateData();
    }

    private void populateData() {
        if (proposal == null) {
            return;
        }

        // Set header information
        lblTotalAmount.setText("Gesamtzahlung: " + currencyFormat.format(proposal.getTotalAmount()) +
                               " vom " + dateFormat.format(proposal.getPaymentDate()));

        // Set table model
        PaymentSplitTableModel model = new PaymentSplitTableModel(proposal.getAllocations());
        tblSplit.setModel(model);

        // Set column widths
        tblSplit.getColumnModel().getColumn(0).setPreferredWidth(40);  // Nr.
        tblSplit.getColumnModel().getColumn(1).setPreferredWidth(200); // Komponente
        tblSplit.getColumnModel().getColumn(2).setPreferredWidth(100); // Zinsen offen (NEW)
        tblSplit.getColumnModel().getColumn(3).setPreferredWidth(100); // Forderungsbetrag offen (NEW)
        tblSplit.getColumnModel().getColumn(4).setPreferredWidth(100); // Zahlung (shifted from 3)
        tblSplit.getColumnModel().getColumn(5).setPreferredWidth(100); // Rest (shifted from 4)
        tblSplit.getColumnModel().getColumn(6).setPreferredWidth(100); // Status (shifted from 5)

        // Right-align numeric columns for better readability
        javax.swing.table.DefaultTableCellRenderer rightRenderer = new javax.swing.table.DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tblSplit.getColumnModel().getColumn(2).setCellRenderer(rightRenderer); // Zinsen offen
        tblSplit.getColumnModel().getColumn(3).setCellRenderer(rightRenderer); // Forderungsbetrag offen
        tblSplit.getColumnModel().getColumn(4).setCellRenderer(rightRenderer); // Zahlung
        tblSplit.getColumnModel().getColumn(5).setCellRenderer(rightRenderer); // Rest

        // Build summary text
        StringBuilder summary = new StringBuilder();
        summary.append("Es werden ").append(proposal.getNumberOfEntries()).append(" Buchungen erstellt:\n\n");

        for (int i = 0; i < proposal.getAllocations().size(); i++) {
            var alloc = proposal.getAllocations().get(i);
            summary.append("• Zahlung ").append(i + 1).append(": ");
            summary.append(alloc.getComponent().getName()).append(" - ");
            summary.append(currencyFormat.format(alloc.getAmount()));
            if (alloc.isFullyPaid()) {
                summary.append(" (vollständig getilgt) ✓");
            } else {
                summary.append(" (Teilzahlung)");
            }
            summary.append("\n");
        }

        if (!proposal.isFollowsLegalOrder()) {
            summary.append("\n⚠ Hinweis: Die Verteilung weicht von der gesetzlichen Tilgungsreihenfolge (§ 366/367 BGB) ab.");
        } else {
            summary.append("\n✓ Die Verteilung folgt der gesetzlichen Tilgungsreihenfolge (§ 366/367 BGB).");
        }

        txtSummary.setText(summary.toString());
    }

    public boolean isApproved() {
        return approved;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTotalAmount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSplit = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSummary = new javax.swing.JTextArea();
        cmdBack = new javax.swing.JButton();
        cmdAdjust = new javax.swing.JButton();
        cmdCreate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zahlungsverteilung - Vorschau");

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        lblTotalAmount.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTotalAmount.setText("Gesamtzahlung: 0,00 € vom 01.01.2025");

        tblSplit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblSplit);

        jLabel2.setText("Zusammenfassung:");

        txtSummary.setEditable(false);
        txtSummary.setColumns(20);
        txtSummary.setRows(5);
        jScrollPane2.setViewportView(txtSummary);

        cmdBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        cmdBack.setText("Zurück");
        cmdBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBackActionPerformed(evt);
            }
        });

        cmdAdjust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons16/material/call_split_20dp_0E72B5.png"))); // NOI18N
        cmdAdjust.setText("Verteilung ändern...");
        cmdAdjust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAdjustActionPerformed(evt);
            }
        });

        cmdCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/agt_action_success.png"))); // NOI18N
        cmdCreate.setText("Buchungen erstellen");
        cmdCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotalAmount)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmdBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                        .addComponent(cmdAdjust)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdCreate)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdBack)
                    .addComponent(cmdAdjust)
                    .addComponent(cmdCreate))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackActionPerformed
        approved = false;
        dispose();
    }//GEN-LAST:event_cmdBackActionPerformed

    private void cmdCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreateActionPerformed
        approved = true;
        dispose();
    }//GEN-LAST:event_cmdCreateActionPerformed

    private void cmdAdjustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAdjustActionPerformed
        // Open edit dialog
        PaymentSplitEditDialog editDialog = new PaymentSplitEditDialog(this, true, proposal);
        editDialog.setVisible(true);

        if (editDialog.isModified()) {
            // Refresh display with modified proposal
            populateData();
        }
    }//GEN-LAST:event_cmdAdjustActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdjust;
    private javax.swing.JButton cmdBack;
    private javax.swing.JButton cmdCreate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JTable tblSplit;
    private javax.swing.JTextArea txtSummary;
    // End of variables declaration//GEN-END:variables
}
