error.loadingcase=Fehler beim Laden der Akte: {0}
error.casenotfound=Die Akte wurde nicht gefunden.
hint.archived=Die Akte {0} ist archiviert. Es können keine Dokumente hinzugefügt werden.
msg.uploaded={0,choice,1#Ein Dokument wurde|1<{0} Dokumente wurden} zur Akte {1} hinzugefügt.
dialog.uploaded=Dokumente hinzugefügt
dialog.error=Fehler
dialog.hint=Hinweis
