/*
 * Copyright (C) 2026 Jens Kutschke
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.jdimension.jlawyer.client.editors.documents.viewer;

import com.jdimension.jlawyer.client.editors.EditorsRegistry;
import com.jdimension.jlawyer.client.events.DocumentAddedEvent;
import com.jdimension.jlawyer.client.events.EventBroker;
import com.jdimension.jlawyer.client.settings.ClientSettings;
import com.jdimension.jlawyer.client.utils.AudioConvertUtils;
import com.jdimension.jlawyer.persistence.ArchiveFileBean;
import com.jdimension.jlawyer.persistence.ArchiveFileDocumentsBean;
import com.jdimension.jlawyer.services.ArchiveFileServiceRemote;
import com.jdimension.jlawyer.services.JLawyerServiceLocator;
import java.awt.event.ActionEvent;
import java.io.ByteArrayInputStream;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.FloatControl;
import javax.sound.sampled.LineEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.Timer;
import org.apache.log4j.Logger;

/**
 * Nur-Lese-Wiedergabe für MP3/OGG-Audiodateien. Dekodiert die Bytes zur
 * verlustfreien Wiedergabe in ein PCM-WAV im Speicher und bietet einen Button
 * an, um die Datei als kanonisches 16-kHz-mono-WAV als NEUES Dokument in
 * derselben Akte zu speichern (Original bleibt unangetastet).
 *
 * @author jens
 */
public class ReadOnlySoundplayerPanel extends javax.swing.JPanel implements PreviewPanel {

    private static final Logger log = Logger.getLogger(ReadOnlySoundplayerPanel.class.getName());

    private String documentId = null;
    private String documentName = null;
    private byte[] content = null;
    /** Auf 16 kHz mono dekodiertes WAV: identisch mit dem, was der
     *  Konvertier-Button in die Akte schreibt — einmal dekodieren, für
     *  Play und Save wiederverwenden. */
    private byte[] standardWav = null;
    private final ArchiveFileBean caseDto;

    private Clip clip;
    private Timer timer;
    private FloatControl volumeControl;

    public ReadOnlySoundplayerPanel(String docId, String docName, ArchiveFileBean caseDto) {
        this.documentId = docId;
        this.documentName = docName;
        this.caseDto = caseDto;
        initComponents();

        try {
            String savedVolume = ClientSettings.getInstance().getConfiguration("soundplayer.volume", "80");
            if (savedVolume != null && !savedVolume.isEmpty()) {
                sliderVolume.setValue(Integer.parseInt(savedVolume));
            }
        } catch (Exception e) {
            log.warn("Could not restore volume setting", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdPlayPause = new javax.swing.JButton();
        cmdStop = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        prgTime = new javax.swing.JProgressBar();
        lblStatus = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sliderVolume = new javax.swing.JSlider();
        cmdConvertToWav = new javax.swing.JButton();
        waveformView = new com.jdimension.jlawyer.client.editors.documents.viewer.WaveformPanel();

        cmdPlayPause.setFont(cmdPlayPause.getFont());
        cmdPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons32/material/baseline_play_circle_black_48dp.png"))); // NOI18N
        cmdPlayPause.setText("Play");
        cmdPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPlayPauseActionPerformed(evt);
            }
        });

        cmdStop.setFont(cmdStop.getFont());
        cmdStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons32/material/baseline_stop_circle_black_48dp.png"))); // NOI18N
        cmdStop.setText("Stop");
        cmdStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStopActionPerformed(evt);
            }
        });

        timeLabel.setFont(timeLabel.getFont());
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("00:00:00");

        lblStatus.setFont(lblStatus.getFont().deriveFont(lblStatus.getFont().getStyle() | java.awt.Font.BOLD));
        lblStatus.setText("   ");

        sliderVolume.setMinorTickSpacing(5);
        sliderVolume.setToolTipText("Lautstärke anpassen");
        sliderVolume.setValue(80);
        sliderVolume.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderVolumeStateChanged(evt);
            }
        });

        cmdConvertToWav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons16/editpaste.png"))); // NOI18N
        cmdConvertToWav.setText("In WAV konvertieren");
        cmdConvertToWav.setToolTipText("Als WAV (16 kHz mono) als neues Dokument in der Akte speichern. Original bleibt erhalten.");
        cmdConvertToWav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConvertToWavActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(waveformView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prgTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cmdPlayPause)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdStop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdConvertToWav)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdPlayPause)
                    .addComponent(cmdStop)
                    .addComponent(sliderVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdConvertToWav))
                .addGap(18, 18, 18)
                .addComponent(waveformView, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prgTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel)
                .addGap(18, 18, 18)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPlayPauseActionPerformed
        togglePlayPause();
    }//GEN-LAST:event_cmdPlayPauseActionPerformed

    private void cmdStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStopActionPerformed
        stop();
    }//GEN-LAST:event_cmdStopActionPerformed

    private void sliderVolumeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderVolumeStateChanged
        updateVolume();
    }//GEN-LAST:event_sliderVolumeStateChanged

    private void cmdConvertToWavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConvertToWavActionPerformed
        convertAndSaveAsWav();
    }//GEN-LAST:event_cmdConvertToWavActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jdimension.jlawyer.client.editors.documents.viewer.WaveformPanel waveformView;
    private javax.swing.JButton cmdConvertToWav;
    private javax.swing.JButton cmdPlayPause;
    private javax.swing.JButton cmdStop;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JProgressBar prgTime;
    private javax.swing.JSlider sliderVolume;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void showStatus(String text) {
        this.lblStatus.setText(text);
    }

    @Override
    public String getDocumentId() {
        return this.documentId;
    }

    @Override
    public void removeNotify() {
        closeAudioResources();
        super.removeNotify();
        stop();
        ClientSettings.getInstance().setConfiguration("soundplayer.volume",
                String.valueOf(sliderVolume.getValue()));
    }

    @Override
    public void showContent(String documentId, byte[] content) {
        closeAudioResources();

        this.documentId = documentId;
        this.content = content;

        if (content == null || content.length == 0) {
            showStatus("Keine Audiodaten vorhanden");
            cmdPlayPause.setEnabled(false);
            cmdStop.setEnabled(false);
            cmdConvertToWav.setEnabled(false);
            return;
        }

        try {
            standardWav = AudioConvertUtils.decodeToStandardWav(content);
        } catch (Exception ex) {
            log.error("Could not decode audio for playback: " + documentName, ex);
            showStatus("Wiedergabe nicht möglich: " + ex.getMessage());
            cmdPlayPause.setEnabled(false);
            cmdStop.setEnabled(false);
            cmdConvertToWav.setEnabled(false);
            return;
        }

        try {
            ByteArrayInputStream byteStream = new ByteArrayInputStream(standardWav);
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(byteStream);

            clip = AudioSystem.getClip();
            clip.open(audioInputStream);

            volumeControl = null;
            updateVolume();
            updateWaveform(standardWav);

            clip.addLineListener((LineEvent event) -> {
                if (event.getType() == LineEvent.Type.STOP && (clip.getMicrosecondPosition() == clip.getMicrosecondLength())) {
                    clip.setMicrosecondPosition(0);
                    javax.swing.SwingUtilities.invokeLater(() -> {
                        if (timer != null) {
                            timer.stop();
                        }
                        updateTimeLabel();
                        cmdPlayPause.setText("Play");
                    });
                }
            });

            this.prgTime.setMinimum(0);
            this.prgTime.setMaximum((int) (clip.getMicrosecondLength() / 1000L / 1000L));
            this.prgTime.setValue(0);

            showStatus("");
        } catch (Exception ex) {
            log.error("Error opening audio clip", ex);
            showStatus("Fehler beim Laden der Audiodatei: " + ex.getMessage());
            cmdPlayPause.setEnabled(false);
            cmdStop.setEnabled(false);
        }

        timer = new Timer(1000, (ActionEvent e) -> updateTimeLabel());
    }

    private void togglePlayPause() {
        if (clip == null) {
            return;
        }
        if (clip.isRunning()) {
            // clip.stop() greift auf die native Audio-Line zu und kann auf
            // Linux/PulseAudio bei großen dekodierten Puffern kurz blockieren
            // — off-EDT laufen lassen, damit die UI reagierbar bleibt.
            cmdPlayPause.setText("Play");
            if (timer != null) {
                timer.stop();
            }
            runOffEdt(() -> clip.stop());
        } else {
            clip.start();
            if (timer != null) {
                timer.start();
            }
            this.cmdPlayPause.setText("Pause");
        }
    }

    private void stop() {
        if (clip == null) {
            return;
        }
        cmdPlayPause.setText("Play");
        if (timer != null) {
            timer.stop();
        }
        runOffEdt(() -> {
            clip.stop();
            clip.setMicrosecondPosition(0);
            javax.swing.SwingUtilities.invokeLater(this::updateTimeLabel);
        });
    }

    private static void runOffEdt(Runnable r) {
        Thread t = new Thread(r, "ReadOnlySoundplayerPanel-clip-op");
        t.setDaemon(true);
        t.start();
    }

    private void closeAudioResources() {
        if (clip != null) {
            try {
                clip.stop();
                clip.flush();
                clip.close();
                clip = null;
            } catch (Exception e) {
                log.warn("Error closing clip", e);
            }
        }
        if (timer != null) {
            timer.stop();
        }
    }

    private void updateTimeLabel() {
        if (clip == null) return;
        long microseconds = clip.getMicrosecondPosition();
        this.prgTime.setValue((int) (clip.getMicrosecondPosition() / 1000L / 1000L));
        long minutes = (microseconds / 1000000) / 60;
        long seconds = (microseconds / 1000000) % 60;
        String timeString = String.format("%02d:%02d", minutes, seconds);
        timeLabel.setText(timeString);
        try {
            if (waveformView != null && clip.getMicrosecondLength() > 0) {
                double frac = clip.getMicrosecondPosition() / (double) clip.getMicrosecondLength();
                waveformView.setPlayheadFraction(frac);
            }
        } catch (Throwable ignore) {
        }
    }

    private void updateWaveform(byte[] wavBytes) {
        if (waveformView == null || wavBytes == null) return;
        try {
            float[] peaks = WaveformPanel.computePeaks(wavBytes, 1500);
            waveformView.setWaveform(peaks);
            waveformView.setSeekListener(fraction -> {
                if (clip != null) {
                    long target = (long) (clip.getMicrosecondLength() * Math.min(1.0, Math.max(0.0, fraction)));
                    try {
                        clip.setMicrosecondPosition(target);
                        updateTimeLabel();
                    } catch (Throwable t) {
                        // ignore seek errors
                    }
                }
            });
            waveformView.setPlayheadFraction(0.0);
        } catch (Exception e) {
            waveformView.setWaveform(new float[0]);
        }
    }

    private void updateVolume() {
        if (clip != null && clip.isOpen()) {
            try {
                if (volumeControl == null) {
                    volumeControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
                }
                int volumePercent = sliderVolume.getValue();
                float gain;
                if (volumePercent == 0) {
                    gain = -80.0f;
                } else {
                    gain = (float) (Math.log10(volumePercent / 100.0) * 20.0);
                    gain = Math.max(-40.0f, Math.min(6.0f, gain));
                }
                volumeControl.setValue(gain);
            } catch (Exception e) {
                log.warn("Error adjusting volume", e);
            }
        }
    }

    private void convertAndSaveAsWav() {
        if (caseDto == null || caseDto.getId() == null) {
            JOptionPane.showMessageDialog(this,
                    "Konvertierung ist nur innerhalb einer geöffneten Akte möglich.",
                    "Konvertierung", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (content == null || content.length == 0 || standardWav == null) {
            return;
        }

        String targetName = deriveWavName(documentName);
        String message = String.format(
                "Datei als WAV (16 kHz mono) als neues Dokument in der Akte speichern?%n%n"
                + "Neuer Dateiname: %s%n"
                + "Original: %s (%s)%n"
                + "Ziel-WAV: %s%n%n"
                + "Das Original bleibt in der Akte erhalten.",
                targetName,
                documentName, formatBytes(content.length),
                formatBytes(standardWav.length));

        int choice = JOptionPane.showConfirmDialog(this, message,
                "In WAV konvertieren", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (choice != JOptionPane.OK_OPTION) {
            return;
        }

        cmdConvertToWav.setEnabled(false);
        showStatus("Speichere WAV in der Akte ...");

        // Die im Wiedergabe-Pfad bereits dekodierten 16 kHz mono-Bytes
        // wiederverwenden statt ein zweites Mal zu dekodieren.
        final byte[] wavBytes = this.standardWav;
        final String caseId = caseDto.getId();

        SwingWorker<ArchiveFileDocumentsBean, Void> worker = new SwingWorker<ArchiveFileDocumentsBean, Void>() {
            @Override
            protected ArchiveFileDocumentsBean doInBackground() throws Exception {
                ClientSettings settings = ClientSettings.getInstance();
                JLawyerServiceLocator locator = JLawyerServiceLocator.getInstance(settings.getLookupProperties());
                ArchiveFileServiceRemote remote = locator.lookupArchiveFileServiceRemote();
                String name = pickAvailableName(remote, caseId, targetName);
                return remote.addDocument(caseId, name, wavBytes, "", null);
            }

            @Override
            protected void done() {
                cmdConvertToWav.setEnabled(true);
                try {
                    ArchiveFileDocumentsBean newDoc = get();
                    EventBroker.getInstance().publishEvent(new DocumentAddedEvent(newDoc));
                    showStatus("Konvertiert und gespeichert als " + newDoc.getName());
                } catch (Exception ex) {
                    log.error("Error converting audio to WAV", ex);
                    showStatus("Konvertierung fehlgeschlagen: " + rootMessage(ex));
                    JOptionPane.showMessageDialog(ReadOnlySoundplayerPanel.this,
                            "Konvertierung fehlgeschlagen: " + rootMessage(ex),
                            "Konvertierung", JOptionPane.ERROR_MESSAGE);
                }
            }
        };
        worker.execute();
    }

    private static String pickAvailableName(ArchiveFileServiceRemote remote, String caseId, String desiredName) throws Exception {
        if (!remote.doesDocumentExist(caseId, desiredName)) {
            return desiredName;
        }
        int dot = desiredName.lastIndexOf('.');
        String stem = (dot > 0) ? desiredName.substring(0, dot) : desiredName;
        String ext = (dot > 0) ? desiredName.substring(dot) : "";
        for (int i = 2; i < 100; i++) {
            String candidate = stem + " (" + i + ")" + ext;
            if (!remote.doesDocumentExist(caseId, candidate)) {
                return candidate;
            }
        }
        throw new IllegalStateException("Kein freier Dateiname gefunden für " + desiredName);
    }

    private static String deriveWavName(String originalName) {
        if (originalName == null || originalName.isEmpty()) {
            return "audio.wav";
        }
        int dot = originalName.lastIndexOf('.');
        String stem = (dot > 0) ? originalName.substring(0, dot) : originalName;
        return stem + ".wav";
    }

    private static String formatBytes(long bytes) {
        if (bytes < 1024L) return bytes + " B";
        double kb = bytes / 1024.0;
        if (kb < 1024.0) return String.format("%.1f KB", kb);
        double mb = kb / 1024.0;
        if (mb < 1024.0) return String.format("%.1f MB", mb);
        return String.format("%.2f GB", mb / 1024.0);
    }

    private static String rootMessage(Throwable t) {
        Throwable cur = t;
        while (cur.getCause() != null && cur.getCause() != cur) {
            cur = cur.getCause();
        }
        return cur.getMessage() != null ? cur.getMessage() : cur.getClass().getSimpleName();
    }

    @Override
    public void dispose() {
    }
}
