/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package org.jlawyer.invoicing;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author jens
 */
public class CountryCodes {

    public static CountryCode getDefaultCountry() {
        return new CountryCode("DE", "Deutschland");
    }

    public static List<CountryCode> getCountryCodes() {

        ArrayList<CountryCode> countries = new ArrayList<>();
        countries.add(new CountryCode("AD", "Andorra"));
        countries.add(new CountryCode("AE", "Vereinigte Arabische Emirate"));
        countries.add(new CountryCode("AF", "Afghanistan"));
        countries.add(new CountryCode("AG", "Antigua und Barbuda"));
        countries.add(new CountryCode("AI", "Anguilla"));
        countries.add(new CountryCode("AL", "Albanien"));
        countries.add(new CountryCode("AM", "Armenien"));
        countries.add(new CountryCode("AO", "Angola"));
        countries.add(new CountryCode("AQ", "Argentinische Antarktis"));
        countries.add(new CountryCode("AR", "Argentinien"));
        countries.add(new CountryCode("AS", "Amerikanisch-Samoa"));
        countries.add(new CountryCode("AT", "Österreich"));
        countries.add(new CountryCode("AU", "Ashmore- und Cartierinseln"));
        countries.add(new CountryCode("AW", "Aruba"));
        countries.add(new CountryCode("AX", "Ålandinseln"));
        countries.add(new CountryCode("AZ", "Aserbaidschan"));
        countries.add(new CountryCode("BA", "Bosnien und Herzegowina"));
        countries.add(new CountryCode("BB", "Barbados"));
        countries.add(new CountryCode("BD", "Bangladesch"));
        countries.add(new CountryCode("BE", "Belgien"));
        countries.add(new CountryCode("BF", "Burkina Faso"));
        countries.add(new CountryCode("BG", "Bulgarien"));
        countries.add(new CountryCode("BH", "Bahrain"));
        countries.add(new CountryCode("BI", "Burundi"));
        countries.add(new CountryCode("BJ", "Benin"));
        countries.add(new CountryCode("BL", "St. Barthélemy"));
        countries.add(new CountryCode("BM", "Bermuda"));
        countries.add(new CountryCode("BN", "Brunei Darussalam"));
        countries.add(new CountryCode("BO", "Plurinationaler Staat Bolivien"));
        countries.add(new CountryCode("BQ", "Bonaire, Saba, St. Eustatius"));
        countries.add(new CountryCode("BR", "Brasilien"));
        countries.add(new CountryCode("BS", "Bahamas"));
        countries.add(new CountryCode("BT", "Bhutan"));
        countries.add(new CountryCode("BV", "Bouvetinsel"));
        countries.add(new CountryCode("BW", "Botsuana"));
        countries.add(new CountryCode("BY", "Weißrussland"));
        countries.add(new CountryCode("BZ", "Belize"));
        countries.add(new CountryCode("CA", "Kanada"));
        countries.add(new CountryCode("CC", "Kokosinseln"));
        countries.add(new CountryCode("CD", "Demokratische Republik Kongo"));
        countries.add(new CountryCode("CF", "Zentralafrikanische Republik"));
        countries.add(new CountryCode("CG", "Kongo"));
        countries.add(new CountryCode("CH", "Schweiz"));
        countries.add(new CountryCode("CI", "Côte d’Ivoire"));
        countries.add(new CountryCode("CK", "Cookinseln"));
        countries.add(new CountryCode("CL", "Chile"));
        countries.add(new CountryCode("CM", "Kamerun"));
        countries.add(new CountryCode("CN", "China"));
        countries.add(new CountryCode("CO", "Kolumbien"));
        countries.add(new CountryCode("CR", "Costa Rica"));
        countries.add(new CountryCode("CU", "Kuba"));
        countries.add(new CountryCode("CV", "Cabo Verde"));
        countries.add(new CountryCode("CW", "Curaçao"));
        countries.add(new CountryCode("CX", "Weihnachtsinsel"));
        countries.add(new CountryCode("CY", "Zypern"));
        countries.add(new CountryCode("CZ", "Tschechien"));
        countries.add(new CountryCode("DE", "Deutschland"));
        countries.add(new CountryCode("DJ", "Dschibuti"));
        countries.add(new CountryCode("DK", "Dänemark"));
        countries.add(new CountryCode("DM", "Dominica"));
        countries.add(new CountryCode("DO", "Dominikanische Republik"));
        countries.add(new CountryCode("DZ", "Algerien"));
        countries.add(new CountryCode("EC", "Ecuador"));
        countries.add(new CountryCode("EE", "Estland"));
        countries.add(new CountryCode("EG", "Ägypten"));
        countries.add(new CountryCode("EH", "Westsahara"));
        countries.add(new CountryCode("ER", "Eritrea"));
        countries.add(new CountryCode("ES", "Spanien"));
        countries.add(new CountryCode("ET", "Äthiopien"));
        countries.add(new CountryCode("FI", "Finnland"));
        countries.add(new CountryCode("FJ", "Fidschi"));
        countries.add(new CountryCode("FK", "Falklandinseln (Malwinen)"));
        countries.add(new CountryCode("FM", "Föderierte Staaten von Mikronesien"));
        countries.add(new CountryCode("FO", "Färöer"));
        countries.add(new CountryCode("FR", "Frankreich"));
        countries.add(new CountryCode("GA", "Gabun"));
        countries.add(new CountryCode("GB", "Akrotiri und Dhekelia"));
        countries.add(new CountryCode("GD", "Grenada"));
        countries.add(new CountryCode("GE", "Georgien"));
        countries.add(new CountryCode("GF", "Französisch-Guayana"));
        countries.add(new CountryCode("GG", "Guernsey"));
        countries.add(new CountryCode("GH", "Ghana"));
        countries.add(new CountryCode("GI", "Gibraltar"));
        countries.add(new CountryCode("GL", "Grönland"));
        countries.add(new CountryCode("GM", "Gambia"));
        countries.add(new CountryCode("GN", "Guinea"));
        countries.add(new CountryCode("GP", "Guadeloupe"));
        countries.add(new CountryCode("GQ", "Äquatorialguinea"));
        countries.add(new CountryCode("GR", "Griechenland"));
        countries.add(new CountryCode("GS", "Südgeorgien und die südlichen Sandwichinseln"));
        countries.add(new CountryCode("GT", "Guatemala"));
        countries.add(new CountryCode("GU", "Guam"));
        countries.add(new CountryCode("GW", "Guinea-Bissau"));
        countries.add(new CountryCode("GY", "Guyana"));
        countries.add(new CountryCode("HK", "Hongkong"));
        countries.add(new CountryCode("HM", "Heard und McDonaldinseln"));
        countries.add(new CountryCode("HN", "Honduras"));
        countries.add(new CountryCode("HR", "Kroatien"));
        countries.add(new CountryCode("HT", "Haiti"));
        countries.add(new CountryCode("HU", "Ungarn"));
        countries.add(new CountryCode("ID", "Indonesien"));
        countries.add(new CountryCode("IE", "Irland"));
        countries.add(new CountryCode("IL", "Israel"));
        countries.add(new CountryCode("IM", "Insel Man"));
        countries.add(new CountryCode("IN", "Indien"));
        countries.add(new CountryCode("IO", "Britisches Territorium im Indischen Ozean"));
        countries.add(new CountryCode("IQ", "Irak"));
        countries.add(new CountryCode("IR", "Islamische Republik Iran"));
        countries.add(new CountryCode("IS", "Island"));
        countries.add(new CountryCode("IT", "Italien"));
        countries.add(new CountryCode("JE", "Jersey"));
        countries.add(new CountryCode("JM", "Jamaika"));
        countries.add(new CountryCode("JO", "Jordanien"));
        countries.add(new CountryCode("JP", "Japan"));
        countries.add(new CountryCode("KE", "Kenia"));
        countries.add(new CountryCode("KG", "Kirgisistan"));
        countries.add(new CountryCode("KH", "Kambodscha"));
        countries.add(new CountryCode("KI", "Kiribati"));
        countries.add(new CountryCode("KM", "Komoren"));
        countries.add(new CountryCode("KN", "St. Kitts und Nevis"));
        countries.add(new CountryCode("KP", "Demokratische Volksrepublik Korea"));
        countries.add(new CountryCode("KR", "Republik Korea"));
        countries.add(new CountryCode("KW", "Kuwait"));
        countries.add(new CountryCode("KY", "Kaimaninseln"));
        countries.add(new CountryCode("KZ", "Kasachstan"));
        countries.add(new CountryCode("LA", "Demokratische Volksrepublik Laos"));
        countries.add(new CountryCode("LB", "Libanon"));
        countries.add(new CountryCode("LC", "St. Lucia"));
        countries.add(new CountryCode("LI", "Liechtenstein"));
        countries.add(new CountryCode("LK", "Sri Lanka"));
        countries.add(new CountryCode("LR", "Liberia"));
        countries.add(new CountryCode("LS", "Lesotho"));
        countries.add(new CountryCode("LT", "Litauen"));
        countries.add(new CountryCode("LU", "Luxemburg"));
        countries.add(new CountryCode("LV", "Lettland"));
        countries.add(new CountryCode("LY", "Libyen"));
        countries.add(new CountryCode("MA", "Marokko"));
        countries.add(new CountryCode("MC", "Monaco"));
        countries.add(new CountryCode("MD", "Republik Moldau"));
        countries.add(new CountryCode("ME", "Montenegro"));
        countries.add(new CountryCode("MF", "St. Martin"));
        countries.add(new CountryCode("MG", "Madagaskar"));
        countries.add(new CountryCode("MH", "Marshallinseln"));
        countries.add(new CountryCode("MK", "ehemalige jugoslawische Republik Mazedonien"));
        countries.add(new CountryCode("ML", "Mali"));
        countries.add(new CountryCode("MM", "Myanmar"));
        countries.add(new CountryCode("MN", "Mongolei"));
        countries.add(new CountryCode("MO", "Macau"));
        countries.add(new CountryCode("MP", "Nördliche Marianen"));
        countries.add(new CountryCode("MQ", "Martinique"));
        countries.add(new CountryCode("MR", "Mauretanien"));
        countries.add(new CountryCode("MS", "Montserrat"));
        countries.add(new CountryCode("MT", "Malta"));
        countries.add(new CountryCode("MU", "Mauritius"));
        countries.add(new CountryCode("MV", "Malediven"));
        countries.add(new CountryCode("MW", "Malawi"));
        countries.add(new CountryCode("MX", "Mexiko"));
        countries.add(new CountryCode("MY", "Malaysia"));
        countries.add(new CountryCode("MZ", "Mosambik"));
        countries.add(new CountryCode("NA", "Namibia"));
        countries.add(new CountryCode("NC", "Neukaledonien"));
        countries.add(new CountryCode("NE", "Niger"));
        countries.add(new CountryCode("NF", "Norfolkinsel"));
        countries.add(new CountryCode("NG", "Nigeria"));
        countries.add(new CountryCode("NI", "Nicaragua"));
        countries.add(new CountryCode("NL", "Niederlande"));
        countries.add(new CountryCode("NO", "Norwegen"));
        countries.add(new CountryCode("NP", "Nepal"));
        countries.add(new CountryCode("NR", "Nauru"));
        countries.add(new CountryCode("NU", "Niue"));
        countries.add(new CountryCode("NZ", "Neuseeland"));
        countries.add(new CountryCode("OM", "Oman"));
        countries.add(new CountryCode("PA", "Panama"));
        countries.add(new CountryCode("PE", "Peru"));
        countries.add(new CountryCode("PF", "Französisch-Polynesien"));
        countries.add(new CountryCode("PG", "Papua-Neuguinea"));
        countries.add(new CountryCode("PH", "Philippinen"));
        countries.add(new CountryCode("PK", "Pakistan"));
        countries.add(new CountryCode("PL", "Polen"));
        countries.add(new CountryCode("PM", "St. Pierre und Miquelon"));
        countries.add(new CountryCode("PN", "Pitcairninseln"));
        countries.add(new CountryCode("PR", "Puerto Rico"));
        countries.add(new CountryCode("PS", "Palästina"));
        countries.add(new CountryCode("PT", "Portugal"));
        countries.add(new CountryCode("PW", "Palau"));
        countries.add(new CountryCode("PY", "Paraguay"));
        countries.add(new CountryCode("QA", "Katar"));
        countries.add(new CountryCode("RE", "Réunion"));
        countries.add(new CountryCode("RO", "Rumänien"));
        countries.add(new CountryCode("RS", "Serbien"));
        countries.add(new CountryCode("RU", "Russische Föderation"));
        countries.add(new CountryCode("RW", "Ruanda"));
        countries.add(new CountryCode("SA", "Saudi-Arabien"));
        countries.add(new CountryCode("SB", "Salomonen"));
        countries.add(new CountryCode("SC", "Seychellen"));
        countries.add(new CountryCode("SD", "Sudan"));
        countries.add(new CountryCode("SE", "Schweden"));
        countries.add(new CountryCode("SG", "Singapur"));
        countries.add(new CountryCode("SH", "St. Helena, Ascension und Tristan da Cunha"));
        countries.add(new CountryCode("SI", "Slowenien"));
        countries.add(new CountryCode("SJ", "Svalbard und Jan Mayen"));
        countries.add(new CountryCode("SK", "Slowakei"));
        countries.add(new CountryCode("SL", "Sierra Leone"));
        countries.add(new CountryCode("SM", "San Marino"));
        countries.add(new CountryCode("SN", "Senegal"));
        countries.add(new CountryCode("SO", "Somalia"));
        countries.add(new CountryCode("SR", "Suriname"));
        countries.add(new CountryCode("SS", "Südsudan"));
        countries.add(new CountryCode("ST", "São Tomé und Príncipe"));
        countries.add(new CountryCode("SV", "El Salvador"));
        countries.add(new CountryCode("SX", "St. Martin"));
        countries.add(new CountryCode("SY", "Arabische Republik Syrien"));
        countries.add(new CountryCode("SZ", "Swasiland"));
        countries.add(new CountryCode("TC", "Turks- und Caicosinseln"));
        countries.add(new CountryCode("TD", "Tschad"));
        countries.add(new CountryCode("TF", "Französische Süd- und Antarktisgebiete"));
        countries.add(new CountryCode("TG", "Togo"));
        countries.add(new CountryCode("TH", "Thailand"));
        countries.add(new CountryCode("TJ", "Tadschikistan"));
        countries.add(new CountryCode("TK", "Tokelau"));
        countries.add(new CountryCode("TL", "Timor-Leste"));
        countries.add(new CountryCode("TM", "Turkmenistan"));
        countries.add(new CountryCode("TN", "Tunesien"));
        countries.add(new CountryCode("TO", "Tonga"));
        countries.add(new CountryCode("TR", "Türkei"));
        countries.add(new CountryCode("TT", "Trinidad und Tobago"));
        countries.add(new CountryCode("TV", "Tuvalu"));
        countries.add(new CountryCode("TW", "Taiwan"));
        countries.add(new CountryCode("TZ", "Vereinigte Republik Tansania"));
        countries.add(new CountryCode("UA", "Ukraine"));
        countries.add(new CountryCode("UG", "Uganda"));
        countries.add(new CountryCode("UM", "Kleinere Amerikanische Überseeinseln"));
        countries.add(new CountryCode("US", "Vereinigte Staaten"));
        countries.add(new CountryCode("UY", "Uruguay"));
        countries.add(new CountryCode("UZ", "Usbekistan"));
        countries.add(new CountryCode("VA", "Vatikanstadt"));
        countries.add(new CountryCode("VC", "St. Vincent und die Grenadinen"));
        countries.add(new CountryCode("VE", "Bolivarische Republik Venezuela"));
        countries.add(new CountryCode("VG", "Britische Jungferninseln"));
        countries.add(new CountryCode("VI", "Amerikanische Jungferninseln"));
        countries.add(new CountryCode("VN", "Vietnam"));
        countries.add(new CountryCode("VU", "Vanuatu"));
        countries.add(new CountryCode("WF", "Wallis und Futuna"));
        countries.add(new CountryCode("WS", "Samoa"));
        countries.add(new CountryCode("YE", "Jemen"));
        countries.add(new CountryCode("YT", "Mayotte"));
        countries.add(new CountryCode("ZA", "Südafrika"));
        countries.add(new CountryCode("ZM", "Sambia"));
        countries.add(new CountryCode("ZW", "Simbabwe"));

        return countries;
    }

}
